# Generated by Django 3.1.5 on 2021-01-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='likes',
            new_name='choices',
        ),
    ]
